import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className = 'navbar'>
          <Link href="/login">  {/* 로그인 페이지로 이동하는 링크 */}
            <a className="login-link">Login</a>  {/* a 태그를 Link 안에 넣기 */}
          </Link>
        </div>
        {children}
        </body>
    </html>
  )
}
